-- In this Section all the data will be found


-- Insert Data into SHOP table

INSERT INTO SHOP (SHOP_ID, SHOP_NAME, SHOP_ADDRESS, PHONE_NUMBER, SHOP_DESCRIPTION, USER_ID, SHOP_IMAGE,SHOP_ADMIN_VERIFICATION,CREATED_AT) VALUES
(SHOP_ID_SEQ.NEXTVAL, 'Bakery Bliss', '606 Flour Rd', 9012345678, 'Freshly baked pastries and bread', 1, 'BakeryBliss.png',1,TO_DATE('2024-05-25', 'YYYY-MM-DD'));

INSERT INTO SHOP (SHOP_ID, SHOP_NAME, SHOP_ADDRESS, PHONE_NUMBER, SHOP_DESCRIPTION, USER_ID, SHOP_IMAGE,SHOP_ADMIN_VERIFICATION,CREATED_AT) VALUES
(SHOP_ID_SEQ.NEXTVAL, 'Fruit Fafer', '456 Veggie Ln', 2345678901, 'Fresh fruits', 2, 'FruitFafer.png',1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO SHOP (SHOP_ID, SHOP_NAME, SHOP_ADDRESS, PHONE_NUMBER, SHOP_DESCRIPTION, USER_ID, SHOP_IMAGE,SHOP_ADMIN_VERIFICATION,CREATED_AT) VALUES
(SHOP_ID_SEQ.NEXTVAL, 'Meat Market', '303 Steak St', 6789012345, 'Premium cuts of meat', 3, 'MeatMarket.png',1,TO_DATE('2024-05-27', 'YYYY-MM-DD'));

INSERT INTO SHOP (SHOP_ID, SHOP_NAME, SHOP_ADDRESS, PHONE_NUMBER, SHOP_DESCRIPTION, USER_ID, SHOP_IMAGE,SHOP_ADMIN_VERIFICATION,CREATED_AT) VALUES
(SHOP_ID_SEQ.NEXTVAL, 'Veggie Paradise', '404 Greenway', 7890123456, 'Organic and fresh vegetables', 4, 'VeggieParadise.png',1,TO_DATE('2024-05-23', 'YYYY-MM-DD'));

INSERT INTO SHOP (SHOP_ID, SHOP_NAME, SHOP_ADDRESS, PHONE_NUMBER, SHOP_DESCRIPTION, USER_ID, SHOP_IMAGE,SHOP_ADMIN_VERIFICATION,CREATED_AT) VALUES
(SHOP_ID_SEQ.NEXTVAL, 'Fish King', '505 Ocean Dr', 8901234567, 'Top quality seafood', 5, 'FishKing.png',1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));


-- Insert data into TRADER TABLE
INSERT INTO TRADER (TRADER_ID, TRADER_FIRST_NAME, TRADER_LAST_NAME, TUSER_NAME, EMAIL_ADDRESS, TRADER_PASSWORD, TRADER_ADDRESS, CONTACT_NO, PRODUCT_CATEGORY, SHOP_NAME, TRADER_IMAGE, IS_VERIFIED, SHOP_ID, TRADER_ADMIN_VERIFICATION) VALUES
(TRADER_ID_SEQ.NEXTVAL, 'John', 'Doe', 'john_doe', 'john.doe@example.com', 123456, '123 Main St', 1234567890, 'Bakery', 'Bakery Bliss', NULL, 1, 1, 1);

INSERT INTO TRADER (TRADER_ID, TRADER_FIRST_NAME, TRADER_LAST_NAME, TUSER_NAME, EMAIL_ADDRESS, TRADER_PASSWORD, TRADER_ADDRESS, CONTACT_NO, PRODUCT_CATEGORY, SHOP_NAME, TRADER_IMAGE, IS_VERIFIED, SHOP_ID, TRADER_ADMIN_VERIFICATION) VALUES
(TRADER_ID_SEQ.NEXTVAL, 'Jane', 'Smith', 'jane_smith', 'jane.smith@example.com', 654321, '456 Elm St', 9876543210, 'Fruits', 'Fruit Fafer', NULL, 1, 2, 1);

INSERT INTO TRADER (TRADER_ID, TRADER_FIRST_NAME, TRADER_LAST_NAME, TUSER_NAME, EMAIL_ADDRESS, TRADER_PASSWORD, TRADER_ADDRESS, CONTACT_NO, PRODUCT_CATEGORY, SHOP_NAME, TRADER_IMAGE, IS_VERIFIED, SHOP_ID, TRADER_ADMIN_VERIFICATION) VALUES
(TRADER_ID_SEQ.NEXTVAL, 'Michael', 'Johnson', 'michael_johnson', 'michael.johnson@example.com', 987654, '789 Oak St', 1239874560, 'Meat', 'Meat Market', NULL, 1, 3, 1);

INSERT INTO TRADER (TRADER_ID, TRADER_FIRST_NAME, TRADER_LAST_NAME, TUSER_NAME, EMAIL_ADDRESS, TRADER_PASSWORD, TRADER_ADDRESS, CONTACT_NO, PRODUCT_CATEGORY, SHOP_NAME, TRADER_IMAGE, IS_VERIFIED, SHOP_ID, TRADER_ADMIN_VERIFICATION) VALUES
(TRADER_ID_SEQ.NEXTVAL, 'Emily', 'Brown', 'emily_brown', 'emily.brown@example.com', 123789, '101 Pine St', 4563217890, 'Vegetables', 'Veggie Paradise', NULL, 1, 4, 1);

INSERT INTO TRADER (TRADER_ID, TRADER_FIRST_NAME, TRADER_LAST_NAME, TUSER_NAME, EMAIL_ADDRESS, TRADER_PASSWORD, TRADER_ADDRESS, CONTACT_NO, PRODUCT_CATEGORY, SHOP_NAME, TRADER_IMAGE, IS_VERIFIED, SHOP_ID, TRADER_ADMIN_VERIFICATION) VALUES
(TRADER_ID_SEQ.NEXTVAL, 'David', 'Martinez', 'david_martinez', 'david.martinez@example.com', 987123, '202 Maple St', 7896541230, 'Fish', 'Fish King', NULL, 1, 5, 1);


-- Insert Data into USER_CLECK table
INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Hari', 'Doe', 'User', 'johndoe', 'haroe@example.com', 'Male', TO_DATE('1985-01-15', 'YYYY-MM-DD'), 1234567890, 'password123', '123 Main St', '1', Null,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Jane', 'Smith', 'User', 'janesmith', 'sita1@example.com', 'Female', TO_DATE('1990-03-22', 'YYYY-MM-DD'), 2345678901, 'password456', '456 Elm St', '1', Null,TO_DATE('2024-05-23', 'YYYY-MM-DD'));

INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Rima', 'Johnson', 'User', 'alicejohnson', 'rim12n@example.com', 'Female', TO_DATE('1978-07-11', 'YYYY-MM-DD'), 3456789012, 'password789', '789 Pine St', '1', Null,TO_DATE('2024-05-22', 'YYYY-MM-DD'));

INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Bob', 'Brown', 'User', 'bobbrown', 'bobbrown@example.com', 'Male', TO_DATE('1982-11-02', 'YYYY-MM-DD'), 4567890123, 'password321', '101 Maple St', '1', Null,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Charlie', 'Davis', 'User', 'charliedavis', 'charliedavis@example.com', 'Male', TO_DATE('1995-05-30', 'YYYY-MM-DD'), 5678901234, 'password654', '202 Oak St', '1', Null,TO_DATE('2024-05-25', 'YYYY-MM-DD'));

INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Eve', 'Miller', 'User', 'evemiller', 'evemiller@example.com', 'Female', TO_DATE('1988-09-19', 'YYYY-MM-DD'), 6789012345, 'password987', '303 Cedar St', '1', Null,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Frank', 'Wilson', 'User', 'frankwilson', 'frankwilson@example.com', 'Male', TO_DATE('1975-02-13', 'YYYY-MM-DD'), 7890123456, 'password000', '404 Birch St', '1', Null,TO_DATE('2024-05-26', 'YYYY-MM-DD'));

INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Grace', 'Lee', 'User', 'gracelee', 'gracelee@example.com', 'Female', TO_DATE('1992-12-05', 'YYYY-MM-DD'), 8901234567, 'password111', '505 Spruce St', '1', Null,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Hank', 'King', 'User', 'hankking', 'hankking@example.com', 'Male', TO_DATE('1980-08-17', 'YYYY-MM-DD'), 9012345678, 'password222', '606 Ash St', '1', Null,TO_DATE('2024-05-23', 'YYYY-MM-DD'));

INSERT INTO USER_CLECK (USER_ID, FIRST_NAME, LAST_NAME, ROLE, UUSER_NAME, EMAIL_ADDRESS, GENDER, DOB, PHONE_NUMBER, PASSWORD, ADDRESS, IS_VERIFIED, USER_IMAGE,CREATED_AT) VALUES
(USER_ID_SEQ.NEXTVAL, 'Ivy', 'Garcia', 'User', 'ivygarcia', 'ivygarcia@example.com', 'Female', TO_DATE('1993-06-25', 'YYYY-MM-DD'), 1230984567, 'password333', '707 Redwood St', '1', Null,TO_DATE('2024-05-24', 'YYYY-MM-DD'));




-- Insert data into PRODUCT table



-----------------------------------------------------------------------------------
--- BAKERY
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Brioche', 5, 20, 'Soft and fluffy brioche bread', 'Contains gluten and dairy', 'Brioche.png', 50, 'Bakery', 1, 1,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Cake', 8, 15, 'Delicious layered cake', 'Contains gluten, dairy, and eggs', 'Cake.png', 30, 'Bakery', 1, 2,1,TO_DATE('2024-05-20', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Cookies', 3, 50, 'Crispy and tasty cookies', 'Contains gluten and dairy', 'Cookies.png', 100, 'Bakery', 1, 3,1,TO_DATE('2024-05-23', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Croissant', 4, 25, 'Buttery and flaky croissant', 'Contains gluten and dairy', 'Croissant.png', 75, 'Bakery', 1, 4,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Cupcakes', 6, 30, 'Sweet and colorful cupcakes', 'Contains gluten, dairy, and eggs', 'Cupcakes.png', 60, 'Bakery', 1, 5,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Donuts', 4, 40, 'Delicious chocolate-glazed donuts', 'Contains gluten and dairy', 'Donuts.png', 80, 'Bakery', 1, 6,1,TO_DATE('2024-05-25', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Swiss Rolls', 7, 10, 'Soft and creamy Swiss rolls', 'Contains gluten, dairy, and eggs', 'SwissRolls.png', 40, 'Bakery', 1, 7,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Muffins', 7, 10, 'Soft and creamy Swiss rolls', 'Contains gluten, dairy, and eggs', 'Muffins.png', 40, 'Bakery', 1, 8,1,TO_DATE('2024-05-22', 'YYYY-MM-DD'));


--FRUITS 
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Bell Pepper', 3, 20, 'Red and yellow bell peppers', 'None', 'BellPepper.png', 50, 'Fruits', 2, 1,1,TO_DATE('2024-05-20', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Orange', 4, 30, 'Seedless oranges', 'None', 'Oranges.png', 40, 'Fruits', 2, 2,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Pineapple', 5, 15, 'Fresh pineapple', 'None', 'Pineapple.png', 60, 'Fruits', 2, 3,1,TO_DATE('2024-05-25', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Banana', 3, 25, 'Ripe bananas', 'None', 'Banana.png', 30, 'Fruits', 2, 4,1,TO_DATE('2024-05-26', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Strawberry', 6, 12, 'Basket of strawberries', 'None', 'Strawberry.png', 70, 'Fruits', 2, 5,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Tomato', 3, 10, 'Red tomatoes', 'None', 'Tomatoes.png', 20, 'Fruits', 2, 6,1,TO_DATE('2024-05-28', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Apple', 5, 40, 'Red apples', 'None', 'Apple.png', 80, 'Fruits', 2, 7,1,TO_DATE('2024-05-25', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Grapes', 4, 8, 'Red seedless grapes', 'None', 'Grapes.png', 50, 'Fruits', 2, 8,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));






--meat shop 
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Bacon', 12, 20, 'Sliced bacon', 'None', 'Bacon.png', 100, 'Meat', 3, 1,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Beef Steaks', 8, 5, 'Prime cut beef steaks', 'None', 'BeefSteaks.png', 30, 'Meat', 3, 2,1,TO_DATE('2024-05-23', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Chicken Breast', 9, 15, 'Boneless, skinless chicken breasts', 'None', 'ChickenBreast.png', 100, 'Meat', 3, 3,1,TO_DATE('2024-05-20', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Ground Beef', 11, 20, 'Lean ground beef', 'None', 'GroundBeef.png', 80, 'Meat', 3, 4,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Lamb Meat', 6, 10, 'Leg of lamb', 'None', 'LambMeat.png', 40, 'Meat', 3, 5,1,TO_DATE('2024-05-22', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Pork Chops', 7, 8, 'Bone-in pork chops', 'None', 'PorkChops.png', 50, 'Meat', 3, 6,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Sausages', 9, 30, 'Italian sausages', 'None', 'Sausages.png', 100, 'Meat', 3, 7,1,TO_DATE('2024-05-27', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Turkey Meat', 5, 7, 'Ground turkey', 'None', 'TurkeyMeat.png', 60, 'Meat', 3, 8,1,TO_DATE('2024-05-26', 'YYYY-MM-DD'));



--VEGETABLE 
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Cabbage', 5, 20, 'Fresh green cabbage', 'None', 'Cabbage.png', 50, 'Vegetables', 4, 1,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Carrot', 6, 25, 'Fresh orange carrots', 'None', 'Carrot.png', 60, 'Vegetables', 4, 2,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Cauliflower', 7, 15, 'Head of cauliflower', 'None', 'Cauliflower.png', 40, 'Vegetables', 4, 3,1,TO_DATE('2024-05-25', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Eggplant', 8, 30, 'Fresh eggplant', 'None', 'Eggplant.png', 30, 'Vegetables', 4, 4,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Garlic', 9, 40, 'Head of garlic', 'None', 'Garlic.png', 70, 'Vegetables', 4, 5,1,TO_DATE('2024-05-22', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Potato', 5, 10, 'Russet potatoes', 'None', 'Potato.png', 80, 'Vegetables', 4, 6,1,TO_DATE('2024-05-26', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Spinach', 6, 12, 'Bag of spinach', 'None', 'Spinach.png', 20, 'Vegetables', 4, 7,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Mushroom', 7, 8, 'Package of white mushrooms', 'None', 'Mushroom.png', 40, 'Vegetables', 4, 8,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));




---FISH
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Clams', 6, 30, 'Fresh clams', 'Contains shellfish', 'Clams.png', 60, 'Fish', 5, 1,1,TO_DATE('2024-05-22', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Ghol Fish', 5, 50, 'Assorted fresh fish', 'None', 'GholFish.png', 100, 'Fish', 5, 2,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Lobster', 9, 20, 'Live lobster', 'Contains shellfish', 'Lobster.png', 40, 'Fish', 5, 3,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Salmon', 8, 25, 'Fresh salmon fillets', 'None', 'Salmon.png', 50, 'Fish', 5, 4,1,TO_DATE('2024-05-23', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Shrimp', 7, 40, 'Fresh shrimp', 'Contains shellfish', 'Shrimp.png', 80, 'Fish', 5, 5,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Sushi', 10, 15, 'Assorted sushi platter', 'Contains fish, shellfish, and soy', 'Sushi.png', 30, 'Fish', 5, 6,1,TO_DATE('2024-05-24', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Swordfish', 8, 20, 'Fresh swordfish steaks', 'None', 'Swordfish.png', 40, 'Fish', 5, 7,1,TO_DATE('2024-05-19', 'YYYY-MM-DD'));

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_QUANTITY, PRODUCT_DESCRIPTION, ALLERGY_INFORMATION, PRODUCT_IMAGE, PRODUCT_STOCK, CATEGORY_NAME, SHOP_ID, USER_ID,PRODUCT_ADMIN_VERIFICATION,CREATED_AT) VALUES
  (PRODUCT_ID_SEQ.NEXTVAL, 'Tuna', 7, 30, 'Fresh tuna fillets', 'None', 'Tuna.png', 60, 'Fish', 5, 8,1,TO_DATE('2024-05-20', 'YYYY-MM-DD'));




---------------------------------------------------------------------------------------





-- Insert Data Into WISHLIST table
INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2024-05-05', 'YYYY-MM-DD'), 1, 1);

INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-02', 'YYYY-MM-DD'), TO_DATE('2024-05-06', 'YYYY-MM-DD'), 1, 2);

INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-03', 'YYYY-MM-DD'), TO_DATE('2024-05-07', 'YYYY-MM-DD'), 1, 3);

INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-04', 'YYYY-MM-DD'), TO_DATE('2024-05-08', 'YYYY-MM-DD'), 1, 4);

INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-05', 'YYYY-MM-DD'), TO_DATE('2024-05-09', 'YYYY-MM-DD'), 1, 5);

INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-06', 'YYYY-MM-DD'), TO_DATE('2024-05-10', 'YYYY-MM-DD'), 1, 6);

INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-07', 'YYYY-MM-DD'), TO_DATE('2024-05-11', 'YYYY-MM-DD'), 1, 7);

INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-08', 'YYYY-MM-DD'), TO_DATE('2024-05-12', 'YYYY-MM-DD'), 1, 8);

INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-09', 'YYYY-MM-DD'), TO_DATE('2024-05-13', 'YYYY-MM-DD'), 1, 9);

INSERT INTO WISHLIST (WISHLIST_ID, WISHLIST_CREATED, WISHLIST_UPDATE, WISHLIST_ITEMS, USER_ID) VALUES
(WISHLIST_ID_SEQ.NEXTVAL, TO_DATE('2024-05-10', 'YYYY-MM-DD'), TO_DATE('2024-05-14', 'YYYY-MM-DD'), 1, 10);


-- Insert Data into PRODUCT_WISHLIST table
INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 1, 1);

INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 1, 2);

INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 2, 3);

INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 2, 4);

INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 3, 5);

INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 3, 6);

INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 4, 7);

INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 4, 8);

INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 5, 9);

INSERT INTO PRODUCT_WISHLIST (PRODUCT_WISHLIST_ID, WISHLIST_ID, PRODUCT_ID) VALUES
(PRODUCT_WISHLIST_ID_SEQ.NEXTVAL, 5, 10);


-- Insert Data into DISCOUNT table
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 1, 1);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL,2, NULL, 2, 2);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 3, 3);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL,2, NULL, 4, 4);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 5, 5);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL, 2,NULL, 6, 6);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 7, 7);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL, 1,NULL, 8, 8);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 9, 9);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL,2, NULL, 10, 10);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES
(DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 6, 11);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES 
(DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 3, 12);

INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 2, 16);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 5, 17);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 8, 18);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 8, 19);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 4, 20);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 4, 21);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 2, 22);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 9, 23);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 8, 24);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 8, 25);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 4, 26);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 9, 27);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 6, 28);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 2, 29);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 7, 30);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 4, 31);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 9, 32);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 2, 33);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 1, 34);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 3, 35);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 3, 36);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 2, NULL, 9, 37);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 7, 38);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 1, NULL, 10, 39);
INSERT INTO DISCOUNT (DISCOUNT_ID, DISCOUNT_AMOUNT, DISCOUNT_PERCENT, USER_ID, PRODUCT_ID) VALUES (DISCOUNT_ID_SEQ.NEXTVAL, 3, NULL, 5, 40);

-- Insert data Into REVIEW table
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-01', 'YYYY-MM-DD'), 4, 'Great product!', 1, 1);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-02', 'YYYY-MM-DD'), 5, 'Very satisfied with the purchase.', 2, 2);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-03', 'YYYY-MM-DD'), 1, 'Could be better.', 3, 3);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-04', 'YYYY-MM-DD'), 4, 'Decent quality.', 4, 4);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-05', 'YYYY-MM-DD'), 5, 'Excellent service!', 5, 5);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-06', 'YYYY-MM-DD'), 2, 'Not what I expected.', 6, 6);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-07', 'YYYY-MM-DD'), 4, 'Good value for money.', 7, 7);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-08', 'YYYY-MM-DD'), 2, 'Highly recommend!', 8, 8);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-09', 'YYYY-MM-DD'), 3, 'Average experience.', 9, 9);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES
(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-10', 'YYYY-MM-DD'), 4, 'Satisfied overall.', 10, 10);

INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-16', 'YYYY-MM-DD'), 1, 'Quality craftsmanship, built to last.', 8, 11);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-14', 'YYYY-MM-DD'), 5, 'The design is sleek and modern, adds a nice touch to my home.', 7, 12);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-02', 'YYYY-MM-DD'), 1, 'Exactly as described, no surprises.', 6, 13);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-29', 'YYYY-MM-DD'), 2, 'Great customer service, very responsive.', 2, 14);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-26', 'YYYY-MM-DD'), 2, 'Shipping took much longer than expected.', 8, 15);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-21', 'YYYY-MM-DD'), 1, 'Great customer service, very responsive.', 2, 16);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-03', 'YYYY-MM-DD'), 5, 'Didn''t meet my expectations, quite underwhelming.', 2, 17);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-07', 'YYYY-MM-DD'), 1, 'Perfect addition to my collection, couldn''t be happier.', 9, 18);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-18', 'YYYY-MM-DD'), 4, 'Sleek and stylish design, adds a modern touch to any room.', 5, 19);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-01', 'YYYY-MM-DD'), 5, 'Difficult to assemble, instructions were unclear.', 4, 20);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-13', 'YYYY-MM-DD'), 5, 'Difficult to assemble, instructions were unclear.', 1, 21);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-24', 'YYYY-MM-DD'), 5, 'Didn''t meet my expectations, quite underwhelming.', 8, 22);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-29', 'YYYY-MM-DD'), 5, 'Not as described, false advertising.', 2, 23);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-10', 'YYYY-MM-DD'), 1, 'Customer service was excellent, resolved my issue quickly.', 2, 24);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-28', 'YYYY-MM-DD'), 3, 'Does exactly what it says it does, highly recommend.', 3, 25);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-08', 'YYYY-MM-DD'), 1, 'Highly versatile product, serves multiple purposes.', 9, 26);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-10', 'YYYY-MM-DD'), 2, 'Arrived damaged, very disappointed.', 8, 27);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-23', 'YYYY-MM-DD'), 2, 'Highly durable, withstands heavy use.', 9, 28);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-27', 'YYYY-MM-DD'), 2, 'Absolutely terrible, do not waste your money.', 2, 29);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-10', 'YYYY-MM-DD'), 2, 'Disappointing purchase, didn''t work as expected.', 7, 30);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-15', 'YYYY-MM-DD'), 2, 'Great investment, will definitely buy again.', 4, 31);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-17', 'YYYY-MM-DD'), 1, 'Sturdy construction, built to withstand wear and tear.', 2, 32);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-21', 'YYYY-MM-DD'), 3, 'Functional and practical, meets my needs perfectly.', 3, 33);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-04', 'YYYY-MM-DD'), 1, 'Works well but overpriced for what it is.', 3, 34);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-14', 'YYYY-MM-DD'), 3, 'Customer service was excellent, resolved my issue quickly.', 10, 35);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-28', 'YYYY-MM-DD'), 4, 'Sleek and stylish design, adds a modern touch to any room.', 8, 36);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-15', 'YYYY-MM-DD'), 5, 'Product arrived damaged, very frustrating.', 8, 37);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-19', 'YYYY-MM-DD'), 3, 'Great customer service, very responsive.', 6, 38);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-21', 'YYYY-MM-DD'), 3, 'Shipping took much longer than expected.', 6, 39);
INSERT INTO REVIEW (REVIEW_ID, REVIEW_DATE, REVIEW_SCORE, REVIEW_COMMENT, USER_ID, PRODUCT_ID) VALUES(REVIEW_ID_SEQ.NEXTVAL, TO_DATE('2024-05-28', 'YYYY-MM-DD'), 4, 'Looks cheap, not worth the money.', 3, 40);


-- Insert data into CART table
INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-01', 'YYYY-MM-DD'), TO_DATE('2024-05-05', 'YYYY-MM-DD'), 5, 1);

INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-02', 'YYYY-MM-DD'), TO_DATE('2024-05-06', 'YYYY-MM-DD'), 3, 2);

INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-03', 'YYYY-MM-DD'), TO_DATE('2024-05-07', 'YYYY-MM-DD'), 7, 3);

INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-04', 'YYYY-MM-DD'), TO_DATE('2024-05-08', 'YYYY-MM-DD'), 4, 4);

INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-05', 'YYYY-MM-DD'), TO_DATE('2024-05-09', 'YYYY-MM-DD'), 6, 5);

INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-06', 'YYYY-MM-DD'), TO_DATE('2024-05-10', 'YYYY-MM-DD'), 2, 6);

INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-07', 'YYYY-MM-DD'), TO_DATE('2024-05-11', 'YYYY-MM-DD'), 8, 7);

INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-08', 'YYYY-MM-DD'), TO_DATE('2024-05-12', 'YYYY-MM-DD'), 5, 8);

INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-09', 'YYYY-MM-DD'), TO_DATE('2024-05-13', 'YYYY-MM-DD'), 3, 9);

INSERT INTO CART (CART_ID, CART_CREATED, CART_UPDATED, CART_ITEMS, USER_ID) VALUES
(CART_ID_SEQ.NEXTVAL, TO_DATE('2024-05-10', 'YYYY-MM-DD'), TO_DATE('2024-05-14', 'YYYY-MM-DD'), 7, 10);


-- Insert data into CART_PRODUCT table
INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 1, 1,8);

INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 1, 2,8);

INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 2, 3,2);

INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 2, 4,8);

INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 3, 5,3);

INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 3, 6,9);

INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 4, 7,6);

INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 4, 8,5);

INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 5, 9,4);

INSERT INTO CART_PRODUCT (CART_PRODUCT_ID, CART_ID, PRODUCT_ID,QUANTITY) VALUES
(CART_PRODUCT_ID_SEQ.NEXTVAL, 5, 10,3);


-- Insert data into COLLECTION_SLOT TABLE
INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL, '13-16', TO_DATE('2024-05-01', 'YYYY-MM-DD'));

INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL, '16-19', TO_DATE('2024-05-01', 'YYYY-MM-DD'));

INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL, '10-13', TO_DATE('2024-05-01', 'YYYY-MM-DD'));

INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL, '16-19', TO_DATE('2024-05-02', 'YYYY-MM-DD'));

INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL,'10-13', TO_DATE('2024-05-02', 'YYYY-MM-DD'));

INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL, '13-16', TO_DATE('2024-05-02', 'YYYY-MM-DD'));

INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL, '16-19', TO_DATE('2024-05-03', 'YYYY-MM-DD'));

INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL, '10-13', TO_DATE('2024-05-03', 'YYYY-MM-DD'));

INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL, '13-16', TO_DATE('2024-05-03', 'YYYY-MM-DD'));

INSERT INTO COLLECTION_SLOT (COLLECTION_SLOT_ID, COLLECTION_TIME, COLLECTION_DATE) VALUES
(COLLECTION_SLOT_ID_SEQ.NEXTVAL, '16-19', TO_DATE('2024-05-04', 'YYYY-MM-DD'));


-- Insert data into ORDERS TABLE
INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 3, TIMESTAMP '2024-05-01 10:00:00', 50, 1001, 1, 1,1,1);

INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 2, TIMESTAMP '2024-05-02 11:00:00', 30, 1002, 2, 2,2,2);

INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 4, TIMESTAMP '2024-05-03 12:00:00', 80, 1003, 3, 3,3,3);

INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 1, TIMESTAMP '2024-05-04 10:00:00', 20, 1004, 4, 4,4,4);

INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 3, TIMESTAMP '2024-05-05 11:00:00', 50, 1005, 5, 5,5,5);

INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 2, TIMESTAMP '2024-05-06 12:00:00', 30, 1006, 6, 6,6,6);

INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 4, TIMESTAMP '2024-05-07 10:00:00', 80, 1007, 7, 7,7,7);

INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 1, TIMESTAMP '2024-05-08 11:00:00', 20, 1008, 8, 8,8,8);

INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 3, TIMESTAMP '2024-05-09 12:00:00', 50, 1009, 9, 9,9,9);

INSERT INTO ORDERS (ORDER_ID, ORDER_QUANTITY, ORDER_DATE, TOTAL_AMOUNT, INVOICE_NO, COLLECTION_SLOT_ID, CART_ID,USER_ID,PRODUCT_ID) VALUES
(ORDER_ID_SEQ.NEXTVAL, 3, TIMESTAMP '2024-05-09 12:00:00', 60, 1009, 10, 10,10,10);



-- Insert data into PAYMENT TABLE
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_AMOUNT, PAID_VIA, PAYMENT_DATE, PAYMENT_TIME, USER_ID, ORDER_ID) VALUES
(PAYMENT_ID_SEQ.NEXTVAL, 100, 'PayPal', DATE '2024-05-01', TIMESTAMP '2024-05-01 10:00:00', 1, 1);

INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_AMOUNT, PAID_VIA, PAYMENT_DATE, PAYMENT_TIME, USER_ID, ORDER_ID) VALUES
(PAYMENT_ID_SEQ.NEXTVAL, 50, 'PayPal', DATE '2024-05-02', TIMESTAMP '2024-05-02 11:00:00', 2, 2);

INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_AMOUNT, PAID_VIA, PAYMENT_DATE, PAYMENT_TIME, USER_ID, ORDER_ID) VALUES
(PAYMENT_ID_SEQ.NEXTVAL, 80, 'PayPal', DATE '2024-05-03', TIMESTAMP '2024-05-03 12:00:00', 3, 3);

INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_AMOUNT, PAID_VIA, PAYMENT_DATE, PAYMENT_TIME, USER_ID, ORDER_ID) VALUES
(PAYMENT_ID_SEQ.NEXTVAL, 30, 'PayPal', DATE '2024-05-04', TIMESTAMP '2024-05-04 10:00:00', 4, 4);

INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_AMOUNT, PAID_VIA, PAYMENT_DATE, PAYMENT_TIME, USER_ID, ORDER_ID) VALUES
(PAYMENT_ID_SEQ.NEXTVAL, 60, 'PayPal', DATE '2024-05-05', TIMESTAMP '2024-05-05 11:00:00', 5, 5);

INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_AMOUNT, PAID_VIA, PAYMENT_DATE, PAYMENT_TIME, USER_ID, ORDER_ID) VALUES
(PAYMENT_ID_SEQ.NEXTVAL, 40, 'PayPal', DATE '2024-05-06', TIMESTAMP '2024-05-06 12:00:00', 6, 6);

INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_AMOUNT, PAID_VIA, PAYMENT_DATE, PAYMENT_TIME, USER_ID, ORDER_ID) VALUES
(PAYMENT_ID_SEQ.NEXTVAL, 70, 'PayPal', DATE '2024-05-07', TIMESTAMP '2024-05-07 10:00:00', 7, 7);

INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_AMOUNT, PAID_VIA, PAYMENT_DATE, PAYMENT_TIME, USER_ID, ORDER_ID) VALUES
(PAYMENT_ID_SEQ.NEXTVAL, 90, 'PayPal', DATE '2024-05-08', TIMESTAMP '2024-05-08 11:00:00', 8, 8);

INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_AMOUNT, PAID_VIA, PAYMENT_DATE, PAYMENT_TIME, USER_ID, ORDER_ID) VALUES
(PAYMENT_ID_SEQ.NEXTVAL, 90, 'PayPal', DATE '2024-05-09', TIMESTAMP '2024-05-09 11:00:00', 9, 9);





-- Insert data into REVIEW_ACCESS table




INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 1, 1,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 2, 1,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 3, 2,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 13, 3,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 2, 4,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 3, 5,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 1, 2,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 29, 3,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 3, 4,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES (ACCESS_ID_SEQ.NEXTVAL, 13, 5,1);

INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 25, 5,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 26, 7,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 34, 8,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 9, 2,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 12, 6,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 8, 1,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 33, 7,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 1, 8,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 13, 1,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 5, 8,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 32, 3,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 29, 7,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 36, 3,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 6, 7,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 34, 4,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 24, 8,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 32, 9,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 13, 7,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 33, 4,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 20, 5,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 19, 7,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 36, 4,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 29, 4,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 23, 3,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 37, 5,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 17, 6,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 36, 7,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 32, 1,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 21, 5,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 13, 10,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 17, 7,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 12, 1,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 26, 2,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 29, 8,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 36, 6,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 29, 3,1);
INSERT INTO REVIEW_ACCESS (ACCESS_ID, PRODUCT_ID, USER_ID,IS_COLLECTED) VALUES(ACCESS_ID_SEQ.NEXTVAL, 17, 5,1);


--------------------------------------------------------------------------------------------------------------

-- Insert data into REVENUE table
INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-10', 'YYYY-MM-DD'), 1000.50, 100, 1, 50, 1);

INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-11', 'YYYY-MM-DD'), 1500.75, 150, 2, 60, 2);

INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-12', 'YYYY-MM-DD'), 1200.00, 120, 3, 70, 3);

INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-13', 'YYYY-MM-DD'), 1300.25, 130, 4, 80, 1);

INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-14', 'YYYY-MM-DD'), 1400.50, 140, 5, 90, 2);

INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-15', 'YYYY-MM-DD'), 1100.75, 110, 6, 100, 3);

INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-16', 'YYYY-MM-DD'), 1250.00, 125, 1, 55, 1);

INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-17', 'YYYY-MM-DD'), 1350.25, 135, 2, 65, 2);

INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-18', 'YYYY-MM-DD'), 1450.50, 145, 3, 75, 3);

INSERT INTO REVENUE (REVENUE_DATE, TOTAL_SALES, TOTAL_ITEMS_SOLD, MOST_SOLD_PRODUCT_ID, MOST_SOLD_PRODUCT_COUNT, TRADER_ID) VALUES 
(TO_DATE('2023-05-19', 'YYYY-MM-DD'), 1550.75, 155, 4, 85, 1);